#!/bin/sh
rm -f initrd-*.img; ./initext initrd

qemu-system-x86_64 -enable-kvm -hda /dev/$1 -m 1024 \
	-kernel vmlinuz -initrd initrd-*.img \
	-net nic,vlan=0 -net user,vlan=0 \
	-append "boot=live config apparmor=1 security=apparmor union=aufs $2" 

